const DAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
const DAY_THEME = {
  Sunday: {
    selectedChip: 'border-rose-300 bg-rose-100 text-rose-800',
    panel: 'border-rose-200 bg-rose-50/40',
    heading: 'text-rose-800'
  },
  Monday: {
    selectedChip: 'border-amber-300 bg-amber-100 text-amber-800',
    panel: 'border-amber-200 bg-amber-50/40',
    heading: 'text-amber-800'
  },
  Tuesday: {
    selectedChip: 'border-lime-300 bg-lime-100 text-lime-800',
    panel: 'border-lime-200 bg-lime-50/40',
    heading: 'text-lime-800'
  },
  Wednesday: {
    selectedChip: 'border-emerald-300 bg-emerald-100 text-emerald-800',
    panel: 'border-emerald-200 bg-emerald-50/40',
    heading: 'text-emerald-800'
  },
  Thursday: {
    selectedChip: 'border-sky-300 bg-sky-100 text-sky-800',
    panel: 'border-sky-200 bg-sky-50/40',
    heading: 'text-sky-800'
  },
  Friday: {
    selectedChip: 'border-indigo-300 bg-indigo-100 text-indigo-800',
    panel: 'border-indigo-200 bg-indigo-50/40',
    heading: 'text-indigo-800'
  },
  Saturday: {
    selectedChip: 'border-violet-300 bg-violet-100 text-violet-800',
    panel: 'border-violet-200 bg-violet-50/40',
    heading: 'text-violet-800'
  }
};

const getHospitalId = (item) => String(item?.hospitalId?._id || item?.hospitalId || '');
const getHospitalName = (item, index) => item?.hospitalId?.name || item?.hospitalName || `Hospital ${index + 1}`;

const normalizeSlot = (slot = {}) => ({
  startTime: String(slot.startTime || '09:00'),
  endTime: String(slot.endTime || '09:30')
});

const normalizeDay = (day = {}) => ({
  day: String(day.day || ''),
  slots: (day.slots || []).map(normalizeSlot)
});

const buildAutoGeneratedSlots = () => {
  const slots = [];
  for (let hour = 9; hour < 17; hour += 1) {
    if (hour === 13) continue;
    const startHour = String(hour).padStart(2, '0');
    const nextHour = String(hour + 1).padStart(2, '0');
    slots.push({ startTime: `${startHour}:00`, endTime: `${startHour}:30` });
    slots.push({ startTime: `${startHour}:30`, endTime: `${nextHour}:00` });
  }
  return slots;
};

const ScheduleView = ({ schedule, onChange }) => {
  const hospitals = Array.isArray(schedule) ? schedule : [];

  const updateHospital = (hospitalIndex, nextSchedule) => {
    onChange(
      hospitals.map((item, index) =>
        index === hospitalIndex
          ? {
              ...item,
              schedule: nextSchedule
            }
          : item
      )
    );
  };

  const toggleDay = (hospitalIndex, dayName) => {
    const current = (hospitals[hospitalIndex]?.schedule || []).map(normalizeDay);
    const exists = current.some((item) => item.day === dayName);
    const next = exists
      ? current.filter((item) => item.day !== dayName)
      : [...current, { day: dayName, slots: [{ startTime: '09:00', endTime: '09:30' }] }];
    const sorted = next.sort((a, b) => DAYS.indexOf(a.day) - DAYS.indexOf(b.day));
    updateHospital(hospitalIndex, sorted);
  };

  const addSlot = (hospitalIndex, dayName) => {
    const current = (hospitals[hospitalIndex]?.schedule || []).map(normalizeDay);
    const next = current.map((item) =>
      item.day === dayName
        ? {
            ...item,
            slots: [...item.slots, { startTime: '09:00', endTime: '09:30' }]
          }
        : item
    );
    updateHospital(hospitalIndex, next);
  };

  const updateSlot = (hospitalIndex, dayName, slotIndex, key, value) => {
    const current = (hospitals[hospitalIndex]?.schedule || []).map(normalizeDay);
    const next = current.map((item) =>
      item.day === dayName
        ? {
            ...item,
            slots: item.slots.map((slot, index) =>
              index === slotIndex ? { ...slot, [key]: value } : slot
            )
          }
        : item
    );
    updateHospital(hospitalIndex, next);
  };

  const removeSlot = (hospitalIndex, dayName, slotIndex) => {
    const current = (hospitals[hospitalIndex]?.schedule || []).map(normalizeDay);
    const next = current.map((item) =>
      item.day === dayName
        ? {
            ...item,
            slots: item.slots.filter((_, index) => index !== slotIndex)
          }
        : item
    );
    updateHospital(hospitalIndex, next);
  };

  const autoGenerateDaySlots = (hospitalIndex, dayName) => {
    const generated = buildAutoGeneratedSlots();
    const current = (hospitals[hospitalIndex]?.schedule || []).map(normalizeDay);
    const next = current.map((item) =>
      item.day === dayName
        ? {
            ...item,
            slots: generated.map((slot) => ({ ...slot }))
          }
        : item
    );
    updateHospital(hospitalIndex, next);
  };

  if (!hospitals.length) {
    return (
      <div className="rounded-2xl bg-white p-5 shadow-card">
        <p className="text-sm text-teal-700">No hospital linked yet. Select hospital in profile first.</p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {hospitals.map((hospitalSchedule, hospitalIndex) => (
        <div key={getHospitalId(hospitalSchedule) || hospitalIndex} className="rounded-2xl bg-white p-5 shadow-card">
          <p className="text-sm text-teal-600">Hospital</p>
          <p className="text-base font-semibold text-ink">{getHospitalName(hospitalSchedule, hospitalIndex)}</p>

          <div className="mt-3 flex flex-wrap gap-2">
            {DAYS.map((day) => {
              const selected = (hospitalSchedule.schedule || []).some((item) => item.day === day);
              const theme = DAY_THEME[day] || DAY_THEME.Sunday;
              return (
                <button
                  key={day}
                  type="button"
                  onClick={() => toggleDay(hospitalIndex, day)}
                  className={`rounded-full border px-3 py-1 text-xs font-medium ${
                    selected
                      ? theme.selectedChip
                      : 'border-teal-200 bg-white text-teal-700'
                  }`}
                >
                  {day}
                </button>
              );
            })}
          </div>

          <div className="mt-4 space-y-4">
            {(hospitalSchedule.schedule || [])
              .slice()
              .sort((a, b) => DAYS.indexOf(a.day) - DAYS.indexOf(b.day))
              .map((daySchedule) => (
                <div
                  key={daySchedule.day}
                  className={`rounded-xl border p-3 ${DAY_THEME[daySchedule.day]?.panel || 'border-teal-100 bg-white'}`}
                >
                  <div className="flex items-center justify-between">
                    <p className={`font-medium ${DAY_THEME[daySchedule.day]?.heading || 'text-ink'}`}>{daySchedule.day}</p>
                    <div className="flex items-center gap-2">
                      <button
                        type="button"
                        onClick={() => autoGenerateDaySlots(hospitalIndex, daySchedule.day)}
                        className="rounded-lg border border-sky-300 px-2 py-1 text-xs text-sky-700"
                      >
                        Auto Generate Slots
                      </button>
                      <button
                        type="button"
                        onClick={() => addSlot(hospitalIndex, daySchedule.day)}
                        className="rounded-lg border border-teal-300 px-2 py-1 text-xs text-teal-700"
                      >
                        Add Slot
                      </button>
                    </div>
                  </div>

                  <div className="mt-2 space-y-2">
                    {(daySchedule.slots || []).map((slot, slotIndex) => (
                      <div key={`${daySchedule.day}-${slotIndex}`} className="grid gap-2 md:grid-cols-[1fr_1fr_auto]">
                        <input
                          type="time"
                          value={slot.startTime || '09:00'}
                          onChange={(e) => updateSlot(hospitalIndex, daySchedule.day, slotIndex, 'startTime', e.target.value)}
                          className="rounded-lg border border-teal-200 px-3 py-2 text-sm"
                        />
                        <input
                          type="time"
                          value={slot.endTime || '09:30'}
                          onChange={(e) => updateSlot(hospitalIndex, daySchedule.day, slotIndex, 'endTime', e.target.value)}
                          className="rounded-lg border border-teal-200 px-3 py-2 text-sm"
                        />
                        <button
                          type="button"
                          onClick={() => removeSlot(hospitalIndex, daySchedule.day, slotIndex)}
                          className="rounded-lg border border-red-200 px-3 py-2 text-sm text-red-600"
                        >
                          Remove
                        </button>
                      </div>
                    ))}
                    {!daySchedule.slots?.length ? (
                      <p className="text-xs text-teal-700">No time slots added yet for this day.</p>
                    ) : null}
                  </div>
                </div>
              ))}
          </div>
        </div>
      ))}
    </div>
  );
};

export default ScheduleView;
